error_handling:
  error_logging: true
  graceful_degradation: true
  max_errors: 100
  retry_failed_items: true
export:
  compression:
    enabled: true
    format: gzip
    level: 6
  formats:
  - json
  - csv
  - excel
ml:
  classification:
    batch_size: 1
    max_length: 512
    timeout: 60
    use_gpu: false
performance:
  connection_pooling: true
  max_concurrent_requests: 4
  max_retries: 3
  memory:
    cleanup_interval: 300
    enable_compression: true
    max_cache_size: 2000
    memory_monitoring: true
  monitoring:
    enabled: true
    log_performance: true
    performance_prediction: true
    real_time_alerts: true
    track_memory: true
  request_delay: 1.0
  timeout: 30
processing:
  enable_ai_enhancement: true
  enable_ensemble_methods: true
  enable_quality_checks: true
  enable_validation: true
  enable_web_validation: true
