// Auto-generated theme definitions
// Generated from Python THEMES dictionary

const availableThemes = [
    {
        name: 'default_dark',
        display_name: 'Default (Dark)',
        category: 'professional',
        background: '#2E2E2E',
        primary: '#5A9BD5',
        emoji: '🌑',
        icon: '🌑',
        splashEffect: 'stars',
        uiEffect: 'nightGlow',
        welcomeMessage: 'Welcome to Flutter Earth',
        splashText: 'Flutter Earth',
        notificationMessage: 'Flutter Earth'
    },
    {
        name: 'light',
        display_name: 'Light',
        category: 'professional',
        background: '#F0F0F0',
        primary: '#0078D7',
        emoji: '🌞',
        icon: '🌞',
        splashEffect: 'sunbeams',
        uiEffect: 'sunshine',
        welcomeMessage: 'Welcome to Flutter Earth',
        splashText: 'Flutter Earth',
        notificationMessage: 'Flutter Earth'
    },
    {
        name: 'sanofi',
        display_name: 'Sanofi Inspired',
        category: 'corporate',
        background: '#FFFFFF',
        primary: '#0064B4',
        emoji: '🌍',
        icon: '🌍',
        splashEffect: 'fade',
        uiEffect: 'none',
        welcomeMessage: 'Welcome to the Platform',
        splashText: 'Flutter Earth Platform',
        notificationMessage: 'Flutter Earth Platform'
    },
    {
        name: 'twilight_sparkle',
        display_name: 'Twilight Sparkle',
        category: 'mlp',
        background: '#2c1a4d',
        primary: '#6c4a8e',
        emoji: '📚',
        icon: '📚',
        splashEffect: 'magic',
        uiEffect: 'magicSparkle',
        welcomeMessage: 'Greetings, Everypony!',
        splashText: 'Twilight's Flutter Earth Study',
        notificationMessage: 'Twilight's Flutter Earth Study'
    },
    {
        name: 'pinkie_pie',
        display_name: 'Pinkie Pie',
        category: 'mlp',
        background: '#ffe6f2',
        primary: '#ff80c0',
        emoji: '🎉',
        icon: '🎉',
        splashEffect: 'confetti',
        uiEffect: 'partyConfetti',
        welcomeMessage: 'Okie Dokie Lokie!',
        splashText: 'Pinkie Pie's Super Duper Party App!',
        notificationMessage: 'Pinkie Pie's Super Duper Party App!'
    },
    {
        name: 'fluttershy',
        display_name: 'Fluttershy',
        category: 'mlp',
        background: '#f3e5f5',
        primary: '#ffb3d9',
        emoji: '🦋',
        icon: '🦋',
        splashEffect: 'fade',
        uiEffect: 'none',
        welcomeMessage: 'Oh, hello there...',
        splashText: 'Fluttershy's Gentle Earth Explorer',
        notificationMessage: 'Fluttershy's Gentle Earth Explorer'
    },
    {
        name: 'rainbow_dash',
        display_name: 'Rainbow Dash',
        category: 'mlp',
        background: '#e3f2fd',
        primary: '#2196f3',
        emoji: '🌈',
        icon: '🌈',
        splashEffect: 'rainbow',
        uiEffect: 'rainbowTrail',
        welcomeMessage: 'Hey there!',
        splashText: 'Rainbow Dash's Awesome Earth Explorer',
        notificationMessage: 'Rainbow Dash's Awesome Earth Explorer'
    },
    {
        name: 'applejack',
        display_name: 'Applejack',
        category: 'mlp',
        background: '#fff3e0',
        primary: '#ff9800',
        emoji: '🍎',
        icon: '🍎',
        splashEffect: 'fade',
        uiEffect: 'none',
        welcomeMessage: 'Howdy!',
        splashText: 'Applejack's Honest Earth Explorer',
        notificationMessage: 'Applejack's Honest Earth Explorer'
    },
    {
        name: 'rarity',
        display_name: 'Rarity',
        category: 'mlp',
        background: '#f3e5f5',
        primary: '#9c27b0',
        emoji: '💎',
        icon: '💎',
        splashEffect: 'fade',
        uiEffect: 'none',
        welcomeMessage: 'Darling!',
        splashText: 'Rarity's Fabulous Earth Explorer',
        notificationMessage: 'Rarity's Fabulous Earth Explorer'
    },
    {
        name: 'princess_celestia',
        display_name: 'Princess Celestia',
        category: 'mlp',
        background: '#fff8e1',
        primary: '#ffd54f',
        emoji: '☀️',
        icon: '☀️',
        splashEffect: 'sunbeams',
        uiEffect: 'sunshine',
        welcomeMessage: 'Greetings, my little pony!',
        splashText: 'Celestia's Solar Surveyor',
        notificationMessage: 'Celestia's Solar Surveyor'
    },
    {
        name: 'princess_luna',
        display_name: 'Princess Luna',
        category: 'mlp',
        background: '#23213a',
        primary: '#3949ab',
        emoji: '🌙',
        icon: '🌙',
        splashEffect: 'stars',
        uiEffect: 'nightGlow',
        welcomeMessage: 'Good evening, dreamer!',
        splashText: 'Luna's Lunar Mapper',
        notificationMessage: 'Luna's Lunar Mapper'
    },
    {
        name: 'trixie',
        display_name: 'Trixie',
        category: 'mlp',
        background: '#e1bee7',
        primary: '#7c43bd',
        emoji: '🎩',
        icon: '🎩',
        splashEffect: 'fade',
        uiEffect: 'none',
        welcomeMessage: 'Behold, the Great and Powerful Trixie!',
        splashText: 'The Great and Powerful Trixie's Map!',
        notificationMessage: 'The Great and Powerful Trixie's Map!'
    },
    {
        name: 'starlight_glimmer',
        display_name: 'Starlight Glimmer',
        category: 'mlp',
        background: '#e0f7fa',
        primary: '#ba68c8',
        emoji: '⭐',
        icon: '⭐',
        splashEffect: 'sunbeams',
        uiEffect: 'sunshine',
        welcomeMessage: 'Welcome, friend!',
        splashText: 'Starlight's Equality Explorer',
        notificationMessage: 'Starlight's Equality Explorer'
    },
    {
        name: 'derpy_hooves',
        display_name: 'Derpy Hooves',
        category: 'mlp',
        background: '#e0e0e0',
        primary: '#ffd600',
        emoji: '🧁',
        icon: '🧁',
        splashEffect: 'fade',
        uiEffect: 'none',
        welcomeMessage: 'Muffins!',
        splashText: 'Derpy's Muffin Mapper',
        notificationMessage: 'Derpy's Muffin Mapper'
    },
    {
        name: 'steve',
        display_name: 'Steve (Minecraft)',
        category: 'minecraft',
        background: '#5a82c8',
        primary: '#3d2d1e',
        emoji: '🧑‍🌾',
        icon: '🧑‍🌾',
        splashEffect: 'blocky',
        uiEffect: 'blockyOverlay',
        welcomeMessage: 'Howdy, Miner!',
        splashText: 'Steve's Blocky World Explorer',
        notificationMessage: 'Steve's Blocky World Explorer'
    },
    {
        name: 'alex_minecraft',
        display_name: 'Alex (Minecraft)',
        category: 'minecraft',
        background: '#6aa038',
        primary: '#b8662c',
        emoji: '🧑‍🦰',
        icon: '🧑‍🦰',
        splashEffect: 'blocky',
        uiEffect: 'blockyOverlay',
        welcomeMessage: 'Hey Explorer!',
        splashText: 'Alex's Adventure Mapper',
        notificationMessage: 'Alex's Adventure Mapper'
    },
    {
        name: 'creeper_minecraft',
        display_name: 'Creeper (Minecraft)',
        category: 'minecraft',
        background: '#2d7a3f',
        primary: '#1a4a25',
        emoji: '💣',
        icon: '💣',
        splashEffect: 'explode',
        uiEffect: 'creeperShake',
        welcomeMessage: 'Sssss...',
        splashText: 'Creeper's Sssssecret Maps',
        notificationMessage: 'Creeper's Sssssecret Maps'
    },
    {
        name: 'enderman_minecraft',
        display_name: 'Enderman (Minecraft)',
        category: 'minecraft',
        background: '#1a1a1a',
        primary: '#330033',
        emoji: '👾',
        icon: '👾',
        splashEffect: 'portal',
        uiEffect: 'nightGlow',
        welcomeMessage: '*Vwoop*',
        splashText: 'Enderman's Teleportation Almanac',
        notificationMessage: 'Enderman's Teleportation Almanac'
    },
    {
        name: 'zombie_minecraft',
        display_name: 'Zombie (Minecraft)',
        category: 'minecraft',
        background: '#4a654e',
        primary: '#3b5340',
        emoji: '🧟',
        icon: '🧟',
        splashEffect: 'fade',
        uiEffect: 'none',
        welcomeMessage: 'Braaaains... I mean, Welcome!',
        splashText: 'Zombie's... Uh... Maps?',
        notificationMessage: 'Zombie's... Uh... Maps?'
    }
];

export { availableThemes };
