// Auto-generated theme definitions
// Generated from Python THEMES dictionary

const availableThemes = [
    {
        name: 'default_dark',
        display_name: 'Default (Dark)',
        category: 'professional',
        background: '#1a1a1a',
        primary: '#4A90E2',
        emoji: '🌑',
        icon: '🌑',
        splashEffect: 'stars',
        uiEffect: 'nightGlow',
        welcomeMessage: 'Welcome to Flutter Earth',
        splashText: 'Flutter Earth',
        notificationMessage: 'Flutter Earth',
        colors: {
        "background": "#1a1a1a",
        "foreground": "#FFFFFF",
        "primary": "#4A90E2",
        "secondary": "#50C878",
        "accent": "#FF6B35",
        "error": "#E74C3C",
        "success": "#27AE60",
        "text": "#F8F9FA",
        "text_subtle": "#ADB5BD",
        "disabled": "#6C757D",
        "widget_bg": "#2D3748",
        "widget_border": "#4A5568",
        "text_on_primary": "#FFFFFF",
        "button_bg": "#4A90E2",
        "button_fg": "#FFFFFF",
        "button_hover_bg": "#357ABD",
        "entry_bg": "#2D3748",
        "entry_fg": "#FFFFFF",
        "entry_border": "#4A5568",
        "list_bg": "#2D3748",
        "list_fg": "#FFFFFF",
        "list_selected_bg": "#4A90E2",
        "list_selected_fg": "#FFFFFF",
        "tooltip_bg": "#2D3748",
        "tooltip_fg": "#FFFFFF",
        "progressbar_bg": "#4A5568",
        "progressbar_fg": "#4A90E2"
},
        catchphrases: {
        "app_title": "Flutter Earth",
        "view_HomeView": "Home",
        "view_MapView": "Map",
        "view_DownloadView": "Download",
        "view_SatelliteInfoView": "Satellite Info",
        "view_IndexAnalysisView": "Index Analysis",
        "view_VectorDownloadView": "Vector Download",
        "view_DataViewerView": "Data Viewer",
        "view_ProgressView": "Progress",
        "view_SettingsView": "Settings",
        "view_AboutView": "About",
        "view_HomeView_Welcome": "Welcome to Flutter Earth",
        "view_HomeView_WelcomeUser": "Welcome, %1",
        "status_gee_ready": "Earth Engine: Ready",
        "status_gee_not_ready": "Earth Engine: Not Authenticated",
        "action_goto_map": "Go to Map",
        "action_goto_download": "Download Data",
        "action_goto_settings": "Settings",
        "dialog_title_info": "Information",
        "desc_SatelliteInfoView": "Detailed information about satellites and sensors.",
        "header_satellite_category": "Satellite / Category",
        "header_type": "Type",
        "placeholder_select_satellite": "Select a satellite for details.",
        "about_hello_user": "Hello, %1!",
        "about_hello_generic": "Hello!",
        "about_developed_by": "Developed by the Flutter Earth Team & Contributors.",
        "action_visit_website": "Visit Project Website",
        "dialog_title_welcome": "Welcome",
        "prompt_enter_name": "Please enter your name:",
        "placeholder_your_name": "Your name",
        "settings_group_theme": "Appearance",
        "settings_label_theme": "Theme:",
        "settings_label_theme_options": "Theme Options:",
        "settings_opt_catchphrases": "Use Character Catchphrases",
        "settings_opt_icons": "Show Special Icons",
        "settings_opt_animations": "Enable Animated Backgrounds",
        "settings_group_general": "General",
        "settings_label_output_dir": "Output Directory:",
        "settings_group_actions": "Actions",
        "action_reload_settings": "Reload Settings",
        "action_clear_cache": "Clear Cache & Logs",
        "dialog_msg_cleanup_complete": "Cache and logs cleared.",
        "dialog_title_cleanup_complete": "Cleanup Complete",
        "status_no_active_downloads": "No active downloads."
},
        options: {
        "use_character_catchphrases": false,
        "show_special_icons": false,
        "enable_animated_background": false
}
    },
    {
        name: 'light',
        display_name: 'Light',
        category: 'professional',
        background: '#F8F9FA',
        primary: '#007BFF',
        emoji: '🌞',
        icon: '🌞',
        splashEffect: 'sunbeams',
        uiEffect: 'sunshine',
        welcomeMessage: 'Welcome to Flutter Earth',
        splashText: 'Flutter Earth',
        notificationMessage: 'Flutter Earth',
        colors: {
        "background": "#F8F9FA",
        "foreground": "#212529",
        "primary": "#007BFF",
        "secondary": "#28A745",
        "accent": "#FD7E14",
        "error": "#DC3545",
        "success": "#28A745",
        "text": "#212529",
        "text_subtle": "#6C757D",
        "disabled": "#ADB5BD",
        "widget_bg": "#FFFFFF",
        "widget_border": "#DEE2E6",
        "text_on_primary": "#FFFFFF",
        "button_bg": "#007BFF",
        "button_fg": "#FFFFFF",
        "button_hover_bg": "#0056B3",
        "entry_bg": "#FFFFFF",
        "entry_fg": "#212529",
        "entry_border": "#CED4DA",
        "list_bg": "#FFFFFF",
        "list_fg": "#212529",
        "list_selected_bg": "#007BFF",
        "list_selected_fg": "#FFFFFF",
        "tooltip_bg": "#343A40",
        "tooltip_fg": "#FFFFFF",
        "progressbar_bg": "#E9ECEF",
        "progressbar_fg": "#007BFF"
},
        catchphrases: {
        "app_title": "Flutter Earth",
        "view_HomeView": "Home",
        "view_MapView": "Map",
        "view_DownloadView": "Download",
        "view_SatelliteInfoView": "Satellite Info",
        "view_IndexAnalysisView": "Index Analysis",
        "view_VectorDownloadView": "Vector Download",
        "view_DataViewerView": "Data Viewer",
        "view_ProgressView": "Progress",
        "view_SettingsView": "Settings",
        "view_AboutView": "About",
        "view_HomeView_Welcome": "Welcome to Flutter Earth",
        "view_HomeView_WelcomeUser": "Welcome, %1",
        "status_gee_ready": "Earth Engine: Ready",
        "status_gee_not_ready": "Earth Engine: Not Authenticated",
        "action_goto_map": "Go to Map",
        "action_goto_download": "Download Data",
        "action_goto_settings": "Settings",
        "dialog_title_info": "Information",
        "desc_SatelliteInfoView": "Detailed information about satellites and sensors.",
        "header_satellite_category": "Satellite / Category",
        "header_type": "Type",
        "placeholder_select_satellite": "Select a satellite for details.",
        "about_hello_user": "Hello, %1!",
        "about_hello_generic": "Hello!",
        "about_developed_by": "Developed by the Flutter Earth Team & Contributors.",
        "action_visit_website": "Visit Project Website",
        "dialog_title_welcome": "Welcome",
        "prompt_enter_name": "Please enter your name:",
        "placeholder_your_name": "Your name",
        "settings_group_theme": "Appearance",
        "settings_label_theme": "Theme:",
        "settings_label_theme_options": "Theme Options:",
        "settings_opt_catchphrases": "Use Character Catchphrases",
        "settings_opt_icons": "Show Special Icons",
        "settings_opt_animations": "Enable Animated Backgrounds",
        "settings_group_general": "General",
        "settings_label_output_dir": "Output Directory:",
        "settings_group_actions": "Actions",
        "action_reload_settings": "Reload Settings",
        "action_clear_cache": "Clear Cache & Logs",
        "dialog_msg_cleanup_complete": "Cache and logs cleared.",
        "dialog_title_cleanup_complete": "Cleanup Complete",
        "status_no_active_downloads": "No active downloads."
},
        options: {
        "use_character_catchphrases": false,
        "show_special_icons": false,
        "enable_animated_background": false
}
    },
    {
        name: 'unity_pride',
        display_name: 'Unity Pride',
        category: 'pride',
        background: '#000000',
        primary: '#FFD700',
        emoji: '🤝',
        icon: '🤝',
        splashEffect: 'rainbow',
        uiEffect: 'rainbowTrail',
        welcomeMessage: 'Welcome to Flutter Earth - Unity',
        splashText: 'Flutter Earth - Unity',
        notificationMessage: 'Flutter Earth - Unity',
        colors: {
        "background": "#000000",
        "foreground": "#FFFFFF",
        "primary": "#FFD700",
        "secondary": "#00FF00",
        "accent": "#FF0000",
        "error": "#FF4444",
        "success": "#00FF00",
        "text": "#FFFFFF",
        "text_subtle": "#CCCCCC",
        "disabled": "#666666",
        "widget_bg": "#1A1A1A",
        "widget_border": "#333333",
        "text_on_primary": "#000000",
        "button_bg": "#FFD700",
        "button_fg": "#000000",
        "button_hover_bg": "#FFED4E",
        "entry_bg": "#1A1A1A",
        "entry_fg": "#FFFFFF",
        "entry_border": "#333333",
        "list_bg": "#1A1A1A",
        "list_fg": "#FFFFFF",
        "list_selected_bg": "#FFD700",
        "list_selected_fg": "#000000",
        "tooltip_bg": "#1A1A1A",
        "tooltip_fg": "#FFFFFF",
        "progressbar_bg": "#333333",
        "progressbar_fg": "#FFD700"
},
        catchphrases: {
        "app_title": "Flutter Earth - Unity",
        "view_HomeView": "Home",
        "view_MapView": "Map",
        "view_DownloadView": "Download",
        "view_SatelliteInfoView": "Satellite Info",
        "view_IndexAnalysisView": "Index Analysis",
        "view_VectorDownloadView": "Vector Download",
        "view_DataViewerView": "Data Viewer",
        "view_ProgressView": "Progress",
        "view_SettingsView": "Settings",
        "view_AboutView": "About",
        "view_HomeView_Welcome": "Welcome to Flutter Earth - Unity",
        "view_HomeView_WelcomeUser": "Welcome, %1",
        "status_gee_ready": "Earth Engine: Ready",
        "status_gee_not_ready": "Earth Engine: Not Authenticated",
        "action_goto_map": "Go to Map",
        "action_goto_download": "Download Data",
        "action_goto_settings": "Settings",
        "dialog_title_info": "Information",
        "desc_SatelliteInfoView": "Detailed information about satellites and sensors.",
        "header_satellite_category": "Satellite / Category",
        "header_type": "Type",
        "placeholder_select_satellite": "Select a satellite for details.",
        "about_hello_user": "Hello, %1!",
        "about_hello_generic": "Hello!",
        "about_developed_by": "Developed by the Flutter Earth Team & Contributors.",
        "action_visit_website": "Visit Project Website",
        "dialog_title_welcome": "Welcome",
        "prompt_enter_name": "Please enter your name:",
        "placeholder_your_name": "Your name",
        "settings_group_theme": "Appearance",
        "settings_label_theme": "Theme:",
        "settings_label_theme_options": "Theme Options:",
        "settings_opt_catchphrases": "Use Character Catchphrases",
        "settings_opt_icons": "Show Special Icons",
        "settings_opt_animations": "Enable Animated Backgrounds",
        "settings_group_general": "General",
        "settings_label_output_dir": "Output Directory:",
        "settings_group_actions": "Actions",
        "action_reload_settings": "Reload Settings",
        "action_clear_cache": "Clear Cache & Logs",
        "dialog_msg_cleanup_complete": "Cache and logs cleared.",
        "dialog_title_cleanup_complete": "Cleanup Complete",
        "status_no_active_downloads": "No active downloads."
},
        options: {
        "use_character_catchphrases": false,
        "show_special_icons": false,
        "enable_animated_background": true
}
    },
    {
        name: 'cyberpunk',
        display_name: 'Cyberpunk',
        category: 'gaming',
        background: '#0A0A0F',
        primary: '#FF0080',
        emoji: '🌍',
        icon: '🌍',
        splashEffect: 'fade',
        uiEffect: 'none',
        welcomeMessage: 'Welcome to Flutter Earth - Cyberpunk',
        splashText: 'Flutter Earth - Cyberpunk',
        notificationMessage: 'Flutter Earth - Cyberpunk',
        colors: {
        "background": "#0A0A0F",
        "foreground": "#00FF41",
        "primary": "#FF0080",
        "secondary": "#00FFFF",
        "accent": "#FF6B35",
        "error": "#FF0040",
        "success": "#00FF41",
        "text": "#00FF41",
        "text_subtle": "#00CC33",
        "disabled": "#004400",
        "widget_bg": "#1A1A2E",
        "widget_border": "#FF0080",
        "text_on_primary": "#000000",
        "button_bg": "#FF0080",
        "button_fg": "#000000",
        "button_hover_bg": "#FF3399",
        "entry_bg": "#1A1A2E",
        "entry_fg": "#00FF41",
        "entry_border": "#FF0080",
        "list_bg": "#1A1A2E",
        "list_fg": "#00FF41",
        "list_selected_bg": "#FF0080",
        "list_selected_fg": "#000000",
        "tooltip_bg": "#1A1A2E",
        "tooltip_fg": "#00FF41",
        "progressbar_bg": "#004400",
        "progressbar_fg": "#00FF41"
},
        catchphrases: {
        "app_title": "Flutter Earth - Cyberpunk",
        "view_HomeView": "Home",
        "view_MapView": "Map",
        "view_DownloadView": "Download",
        "view_SatelliteInfoView": "Satellite Info",
        "view_IndexAnalysisView": "Index Analysis",
        "view_VectorDownloadView": "Vector Download",
        "view_DataViewerView": "Data Viewer",
        "view_ProgressView": "Progress",
        "view_SettingsView": "Settings",
        "view_AboutView": "About",
        "view_HomeView_Welcome": "Welcome to Flutter Earth - Cyberpunk",
        "view_HomeView_WelcomeUser": "Welcome, %1",
        "status_gee_ready": "Earth Engine: Ready",
        "status_gee_not_ready": "Earth Engine: Not Authenticated",
        "action_goto_map": "Go to Map",
        "action_goto_download": "Download Data",
        "action_goto_settings": "Settings",
        "dialog_title_info": "Information",
        "desc_SatelliteInfoView": "Detailed information about satellites and sensors.",
        "header_satellite_category": "Satellite / Category",
        "header_type": "Type",
        "placeholder_select_satellite": "Select a satellite for details.",
        "about_hello_user": "Hello, %1!",
        "about_hello_generic": "Hello!",
        "about_developed_by": "Developed by the Flutter Earth Team & Contributors.",
        "action_visit_website": "Visit Project Website",
        "dialog_title_welcome": "Welcome",
        "prompt_enter_name": "Please enter your name:",
        "placeholder_your_name": "Your name",
        "settings_group_theme": "Appearance",
        "settings_label_theme": "Theme:",
        "settings_label_theme_options": "Theme Options:",
        "settings_opt_catchphrases": "Use Character Catchphrases",
        "settings_opt_icons": "Show Special Icons",
        "settings_opt_animations": "Enable Animated Backgrounds",
        "settings_group_general": "General",
        "settings_label_output_dir": "Output Directory:",
        "settings_group_actions": "Actions",
        "action_reload_settings": "Reload Settings",
        "action_clear_cache": "Clear Cache & Logs",
        "dialog_msg_cleanup_complete": "Cache and logs cleared.",
        "dialog_title_cleanup_complete": "Cleanup Complete",
        "status_no_active_downloads": "No active downloads."
},
        options: {
        "use_character_catchphrases": false,
        "show_special_icons": false,
        "enable_animated_background": true
}
    },
    {
        name: 'ocean_depths',
        display_name: 'Ocean Depths',
        category: 'nature',
        background: '#001B2E',
        primary: '#00B4D8',
        emoji: '🌍',
        icon: '🌍',
        splashEffect: 'fade',
        uiEffect: 'none',
        welcomeMessage: 'Welcome to Flutter Earth - Ocean',
        splashText: 'Flutter Earth - Ocean',
        notificationMessage: 'Flutter Earth - Ocean',
        colors: {
        "background": "#001B2E",
        "foreground": "#FFFFFF",
        "primary": "#00B4D8",
        "secondary": "#90E0EF",
        "accent": "#CAF0F8",
        "error": "#FF6B6B",
        "success": "#4ECDC4",
        "text": "#E0F4FF",
        "text_subtle": "#90E0EF",
        "disabled": "#023E8A",
        "widget_bg": "#003554",
        "widget_border": "#0077B6",
        "text_on_primary": "#001B2E",
        "button_bg": "#00B4D8",
        "button_fg": "#001B2E",
        "button_hover_bg": "#90E0EF",
        "entry_bg": "#003554",
        "entry_fg": "#E0F4FF",
        "entry_border": "#0077B6",
        "list_bg": "#003554",
        "list_fg": "#E0F4FF",
        "list_selected_bg": "#00B4D8",
        "list_selected_fg": "#001B2E",
        "tooltip_bg": "#003554",
        "tooltip_fg": "#E0F4FF",
        "progressbar_bg": "#0077B6",
        "progressbar_fg": "#00B4D8"
},
        catchphrases: {
        "app_title": "Flutter Earth - Ocean",
        "view_HomeView": "Home",
        "view_MapView": "Map",
        "view_DownloadView": "Download",
        "view_SatelliteInfoView": "Satellite Info",
        "view_IndexAnalysisView": "Index Analysis",
        "view_VectorDownloadView": "Vector Download",
        "view_DataViewerView": "Data Viewer",
        "view_ProgressView": "Progress",
        "view_SettingsView": "Settings",
        "view_AboutView": "About",
        "view_HomeView_Welcome": "Welcome to Flutter Earth - Ocean",
        "view_HomeView_WelcomeUser": "Welcome, %1",
        "status_gee_ready": "Earth Engine: Ready",
        "status_gee_not_ready": "Earth Engine: Not Authenticated",
        "action_goto_map": "Go to Map",
        "action_goto_download": "Download Data",
        "action_goto_settings": "Settings",
        "dialog_title_info": "Information",
        "desc_SatelliteInfoView": "Detailed information about satellites and sensors.",
        "header_satellite_category": "Satellite / Category",
        "header_type": "Type",
        "placeholder_select_satellite": "Select a satellite for details.",
        "about_hello_user": "Hello, %1!",
        "about_hello_generic": "Hello!",
        "about_developed_by": "Developed by the Flutter Earth Team & Contributors.",
        "action_visit_website": "Visit Project Website",
        "dialog_title_welcome": "Welcome",
        "prompt_enter_name": "Please enter your name:",
        "placeholder_your_name": "Your name",
        "settings_group_theme": "Appearance",
        "settings_label_theme": "Theme:",
        "settings_label_theme_options": "Theme Options:",
        "settings_opt_catchphrases": "Use Character Catchphrases",
        "settings_opt_icons": "Show Special Icons",
        "settings_opt_animations": "Enable Animated Backgrounds",
        "settings_group_general": "General",
        "settings_label_output_dir": "Output Directory:",
        "settings_group_actions": "Actions",
        "action_reload_settings": "Reload Settings",
        "action_clear_cache": "Clear Cache & Logs",
        "dialog_msg_cleanup_complete": "Cache and logs cleared.",
        "dialog_title_cleanup_complete": "Cleanup Complete",
        "status_no_active_downloads": "No active downloads."
},
        options: {
        "use_character_catchphrases": false,
        "show_special_icons": false,
        "enable_animated_background": true
}
    },
    {
        name: 'sunset_vibes',
        display_name: 'Sunset Vibes',
        category: 'nature',
        background: '#2C1810',
        primary: '#FF6B35',
        emoji: '🌍',
        icon: '🌍',
        splashEffect: 'fade',
        uiEffect: 'none',
        welcomeMessage: 'Welcome to Flutter Earth - Sunset',
        splashText: 'Flutter Earth - Sunset',
        notificationMessage: 'Flutter Earth - Sunset',
        colors: {
        "background": "#2C1810",
        "foreground": "#FFFFFF",
        "primary": "#FF6B35",
        "secondary": "#F7931E",
        "accent": "#FFD23F",
        "error": "#E74C3C",
        "success": "#27AE60",
        "text": "#FFF8E7",
        "text_subtle": "#F4D03F",
        "disabled": "#8B4513",
        "widget_bg": "#3D2314",
        "widget_border": "#D35400",
        "text_on_primary": "#2C1810",
        "button_bg": "#FF6B35",
        "button_fg": "#2C1810",
        "button_hover_bg": "#F7931E",
        "entry_bg": "#3D2314",
        "entry_fg": "#FFF8E7",
        "entry_border": "#D35400",
        "list_bg": "#3D2314",
        "list_fg": "#FFF8E7",
        "list_selected_bg": "#FF6B35",
        "list_selected_fg": "#2C1810",
        "tooltip_bg": "#3D2314",
        "tooltip_fg": "#FFF8E7",
        "progressbar_bg": "#8B4513",
        "progressbar_fg": "#FF6B35"
},
        catchphrases: {
        "app_title": "Flutter Earth - Sunset",
        "view_HomeView": "Home",
        "view_MapView": "Map",
        "view_DownloadView": "Download",
        "view_SatelliteInfoView": "Satellite Info",
        "view_IndexAnalysisView": "Index Analysis",
        "view_VectorDownloadView": "Vector Download",
        "view_DataViewerView": "Data Viewer",
        "view_ProgressView": "Progress",
        "view_SettingsView": "Settings",
        "view_AboutView": "About",
        "view_HomeView_Welcome": "Welcome to Flutter Earth - Sunset",
        "view_HomeView_WelcomeUser": "Welcome, %1",
        "status_gee_ready": "Earth Engine: Ready",
        "status_gee_not_ready": "Earth Engine: Not Authenticated",
        "action_goto_map": "Go to Map",
        "action_goto_download": "Download Data",
        "action_goto_settings": "Settings",
        "dialog_title_info": "Information",
        "desc_SatelliteInfoView": "Detailed information about satellites and sensors.",
        "header_satellite_category": "Satellite / Category",
        "header_type": "Type",
        "placeholder_select_satellite": "Select a satellite for details.",
        "about_hello_user": "Hello, %1!",
        "about_hello_generic": "Hello!",
        "about_developed_by": "Developed by the Flutter Earth Team & Contributors.",
        "action_visit_website": "Visit Project Website",
        "dialog_title_welcome": "Welcome",
        "prompt_enter_name": "Please enter your name:",
        "placeholder_your_name": "Your name",
        "settings_group_theme": "Appearance",
        "settings_label_theme": "Theme:",
        "settings_label_theme_options": "Theme Options:",
        "settings_opt_catchphrases": "Use Character Catchphrases",
        "settings_opt_icons": "Show Special Icons",
        "settings_opt_animations": "Enable Animated Backgrounds",
        "settings_group_general": "General",
        "settings_label_output_dir": "Output Directory:",
        "settings_group_actions": "Actions",
        "action_reload_settings": "Reload Settings",
        "action_clear_cache": "Clear Cache & Logs",
        "dialog_msg_cleanup_complete": "Cache and logs cleared.",
        "dialog_title_cleanup_complete": "Cleanup Complete",
        "status_no_active_downloads": "No active downloads."
},
        options: {
        "use_character_catchphrases": false,
        "show_special_icons": false,
        "enable_animated_background": true
}
    },
    {
        name: 'forest_mist',
        display_name: 'Forest Mist',
        category: 'nature',
        background: '#1B4332',
        primary: '#52B788',
        emoji: '🌍',
        icon: '🌍',
        splashEffect: 'fade',
        uiEffect: 'none',
        welcomeMessage: 'Welcome to Flutter Earth - Forest',
        splashText: 'Flutter Earth - Forest',
        notificationMessage: 'Flutter Earth - Forest',
        colors: {
        "background": "#1B4332",
        "foreground": "#FFFFFF",
        "primary": "#52B788",
        "secondary": "#95D5B2",
        "accent": "#D4EDDA",
        "error": "#E74C3C",
        "success": "#27AE60",
        "text": "#F8F9FA",
        "text_subtle": "#B7E4C7",
        "disabled": "#40916C",
        "widget_bg": "#2D6A4F",
        "widget_border": "#74C69D",
        "text_on_primary": "#1B4332",
        "button_bg": "#52B788",
        "button_fg": "#1B4332",
        "button_hover_bg": "#74C69D",
        "entry_bg": "#2D6A4F",
        "entry_fg": "#F8F9FA",
        "entry_border": "#74C69D",
        "list_bg": "#2D6A4F",
        "list_fg": "#F8F9FA",
        "list_selected_bg": "#52B788",
        "list_selected_fg": "#1B4332",
        "tooltip_bg": "#2D6A4F",
        "tooltip_fg": "#F8F9FA",
        "progressbar_bg": "#40916C",
        "progressbar_fg": "#52B788"
},
        catchphrases: {
        "app_title": "Flutter Earth - Forest",
        "view_HomeView": "Home",
        "view_MapView": "Map",
        "view_DownloadView": "Download",
        "view_SatelliteInfoView": "Satellite Info",
        "view_IndexAnalysisView": "Index Analysis",
        "view_VectorDownloadView": "Vector Download",
        "view_DataViewerView": "Data Viewer",
        "view_ProgressView": "Progress",
        "view_SettingsView": "Settings",
        "view_AboutView": "About",
        "view_HomeView_Welcome": "Welcome to Flutter Earth - Forest",
        "view_HomeView_WelcomeUser": "Welcome, %1",
        "status_gee_ready": "Earth Engine: Ready",
        "status_gee_not_ready": "Earth Engine: Not Authenticated",
        "action_goto_map": "Go to Map",
        "action_goto_download": "Download Data",
        "action_goto_settings": "Settings",
        "dialog_title_info": "Information",
        "desc_SatelliteInfoView": "Detailed information about satellites and sensors.",
        "header_satellite_category": "Satellite / Category",
        "header_type": "Type",
        "placeholder_select_satellite": "Select a satellite for details.",
        "about_hello_user": "Hello, %1!",
        "about_hello_generic": "Hello!",
        "about_developed_by": "Developed by the Flutter Earth Team & Contributors.",
        "action_visit_website": "Visit Project Website",
        "dialog_title_welcome": "Welcome",
        "prompt_enter_name": "Please enter your name:",
        "placeholder_your_name": "Your name",
        "settings_group_theme": "Appearance",
        "settings_label_theme": "Theme:",
        "settings_label_theme_options": "Theme Options:",
        "settings_opt_catchphrases": "Use Character Catchphrases",
        "settings_opt_icons": "Show Special Icons",
        "settings_opt_animations": "Enable Animated Backgrounds",
        "settings_group_general": "General",
        "settings_label_output_dir": "Output Directory:",
        "settings_group_actions": "Actions",
        "action_reload_settings": "Reload Settings",
        "action_clear_cache": "Clear Cache & Logs",
        "dialog_msg_cleanup_complete": "Cache and logs cleared.",
        "dialog_title_cleanup_complete": "Cleanup Complete",
        "status_no_active_downloads": "No active downloads."
},
        options: {
        "use_character_catchphrases": false,
        "show_special_icons": false,
        "enable_animated_background": true
}
    },
    {
        name: 'neon_dreams',
        display_name: 'Neon Dreams',
        category: 'gaming',
        background: '#0A0A0A',
        primary: '#FF00FF',
        emoji: '🌍',
        icon: '🌍',
        splashEffect: 'fade',
        uiEffect: 'none',
        welcomeMessage: 'Welcome to Flutter Earth - Neon',
        splashText: 'Flutter Earth - Neon',
        notificationMessage: 'Flutter Earth - Neon',
        colors: {
        "background": "#0A0A0A",
        "foreground": "#FFFFFF",
        "primary": "#FF00FF",
        "secondary": "#00FFFF",
        "accent": "#FFFF00",
        "error": "#FF0000",
        "success": "#00FF00",
        "text": "#FFFFFF",
        "text_subtle": "#CCCCCC",
        "disabled": "#666666",
        "widget_bg": "#1A1A1A",
        "widget_border": "#FF00FF",
        "text_on_primary": "#000000",
        "button_bg": "#FF00FF",
        "button_fg": "#000000",
        "button_hover_bg": "#FF33FF",
        "entry_bg": "#1A1A1A",
        "entry_fg": "#FFFFFF",
        "entry_border": "#FF00FF",
        "list_bg": "#1A1A1A",
        "list_fg": "#FFFFFF",
        "list_selected_bg": "#FF00FF",
        "list_selected_fg": "#000000",
        "tooltip_bg": "#1A1A1A",
        "tooltip_fg": "#FFFFFF",
        "progressbar_bg": "#333333",
        "progressbar_fg": "#FF00FF"
},
        catchphrases: {
        "app_title": "Flutter Earth - Neon",
        "view_HomeView": "Home",
        "view_MapView": "Map",
        "view_DownloadView": "Download",
        "view_SatelliteInfoView": "Satellite Info",
        "view_IndexAnalysisView": "Index Analysis",
        "view_VectorDownloadView": "Vector Download",
        "view_DataViewerView": "Data Viewer",
        "view_ProgressView": "Progress",
        "view_SettingsView": "Settings",
        "view_AboutView": "About",
        "view_HomeView_Welcome": "Welcome to Flutter Earth - Neon",
        "view_HomeView_WelcomeUser": "Welcome, %1",
        "status_gee_ready": "Earth Engine: Ready",
        "status_gee_not_ready": "Earth Engine: Not Authenticated",
        "action_goto_map": "Go to Map",
        "action_goto_download": "Download Data",
        "action_goto_settings": "Settings",
        "dialog_title_info": "Information",
        "desc_SatelliteInfoView": "Detailed information about satellites and sensors.",
        "header_satellite_category": "Satellite / Category",
        "header_type": "Type",
        "placeholder_select_satellite": "Select a satellite for details.",
        "about_hello_user": "Hello, %1!",
        "about_hello_generic": "Hello!",
        "about_developed_by": "Developed by the Flutter Earth Team & Contributors.",
        "action_visit_website": "Visit Project Website",
        "dialog_title_welcome": "Welcome",
        "prompt_enter_name": "Please enter your name:",
        "placeholder_your_name": "Your name",
        "settings_group_theme": "Appearance",
        "settings_label_theme": "Theme:",
        "settings_label_theme_options": "Theme Options:",
        "settings_opt_catchphrases": "Use Character Catchphrases",
        "settings_opt_icons": "Show Special Icons",
        "settings_opt_animations": "Enable Animated Backgrounds",
        "settings_group_general": "General",
        "settings_label_output_dir": "Output Directory:",
        "settings_group_actions": "Actions",
        "action_reload_settings": "Reload Settings",
        "action_clear_cache": "Clear Cache & Logs",
        "dialog_msg_cleanup_complete": "Cache and logs cleared.",
        "dialog_title_cleanup_complete": "Cleanup Complete",
        "status_no_active_downloads": "No active downloads."
},
        options: {
        "use_character_catchphrases": false,
        "show_special_icons": false,
        "enable_animated_background": true
}
    },
    {
        name: 'aurora_borealis',
        display_name: 'Aurora Borealis',
        category: 'nature',
        background: '#0B1426',
        primary: '#00FF88',
        emoji: '🌍',
        icon: '🌍',
        splashEffect: 'fade',
        uiEffect: 'none',
        welcomeMessage: 'Welcome to Flutter Earth - Aurora',
        splashText: 'Flutter Earth - Aurora',
        notificationMessage: 'Flutter Earth - Aurora',
        colors: {
        "background": "#0B1426",
        "foreground": "#FFFFFF",
        "primary": "#00FF88",
        "secondary": "#00D4FF",
        "accent": "#FF00FF",
        "error": "#FF4444",
        "success": "#00FF88",
        "text": "#E0F7FF",
        "text_subtle": "#B0E0E6",
        "disabled": "#4A5568",
        "widget_bg": "#1A2332",
        "widget_border": "#00FF88",
        "text_on_primary": "#0B1426",
        "button_bg": "#00FF88",
        "button_fg": "#0B1426",
        "button_hover_bg": "#00D4FF",
        "entry_bg": "#1A2332",
        "entry_fg": "#E0F7FF",
        "entry_border": "#00FF88",
        "list_bg": "#1A2332",
        "list_fg": "#E0F7FF",
        "list_selected_bg": "#00FF88",
        "list_selected_fg": "#0B1426",
        "tooltip_bg": "#1A2332",
        "tooltip_fg": "#E0F7FF",
        "progressbar_bg": "#2D3748",
        "progressbar_fg": "#00FF88"
},
        catchphrases: {
        "app_title": "Flutter Earth - Aurora",
        "view_HomeView": "Home",
        "view_MapView": "Map",
        "view_DownloadView": "Download",
        "view_SatelliteInfoView": "Satellite Info",
        "view_IndexAnalysisView": "Index Analysis",
        "view_VectorDownloadView": "Vector Download",
        "view_DataViewerView": "Data Viewer",
        "view_ProgressView": "Progress",
        "view_SettingsView": "Settings",
        "view_AboutView": "About",
        "view_HomeView_Welcome": "Welcome to Flutter Earth - Aurora",
        "view_HomeView_WelcomeUser": "Welcome, %1",
        "status_gee_ready": "Earth Engine: Ready",
        "status_gee_not_ready": "Earth Engine: Not Authenticated",
        "action_goto_map": "Go to Map",
        "action_goto_download": "Download Data",
        "action_goto_settings": "Settings",
        "dialog_title_info": "Information",
        "desc_SatelliteInfoView": "Detailed information about satellites and sensors.",
        "header_satellite_category": "Satellite / Category",
        "header_type": "Type",
        "placeholder_select_satellite": "Select a satellite for details.",
        "about_hello_user": "Hello, %1!",
        "about_hello_generic": "Hello!",
        "about_developed_by": "Developed by the Flutter Earth Team & Contributors.",
        "action_visit_website": "Visit Project Website",
        "dialog_title_welcome": "Welcome",
        "prompt_enter_name": "Please enter your name:",
        "placeholder_your_name": "Your name",
        "settings_group_theme": "Appearance",
        "settings_label_theme": "Theme:",
        "settings_label_theme_options": "Theme Options:",
        "settings_opt_catchphrases": "Use Character Catchphrases",
        "settings_opt_icons": "Show Special Icons",
        "settings_opt_animations": "Enable Animated Backgrounds",
        "settings_group_general": "General",
        "settings_label_output_dir": "Output Directory:",
        "settings_group_actions": "Actions",
        "action_reload_settings": "Reload Settings",
        "action_clear_cache": "Clear Cache & Logs",
        "dialog_msg_cleanup_complete": "Cache and logs cleared.",
        "dialog_title_cleanup_complete": "Cleanup Complete",
        "status_no_active_downloads": "No active downloads."
},
        options: {
        "use_character_catchphrases": false,
        "show_special_icons": false,
        "enable_animated_background": true
}
    },
    {
        name: 'twilight_sparkle',
        display_name: 'Twilight Sparkle',
        category: 'mlp',
        background: '#6A4FB6',
        primary: '#E1BEE7',
        emoji: '📚',
        icon: '📚',
        splashEffect: 'magic',
        uiEffect: 'magicSparkle',
        welcomeMessage: 'Welcome to the Magic of Friendship!',
        splashText: 'Flutter Earth - Twilight Sparkle',
        notificationMessage: 'Flutter Earth - Twilight Sparkle',
        colors: {
        "background": "#6A4FB6",
        "foreground": "#FFFFFF",
        "primary": "#E1BEE7",
        "secondary": "#FFD54F",
        "accent": "#CE93D8",
        "error": "#D32F2F",
        "success": "#7E57C2",
        "text": "#FFFFFF",
        "text_subtle": "#B39DDB",
        "disabled": "#BDBDBD",
        "widget_bg": "#7E57C2",
        "widget_border": "#9575CD",
        "text_on_primary": "#6A4FB6",
        "button_bg": "#E1BEE7",
        "button_fg": "#6A4FB6",
        "button_hover_bg": "#9575CD",
        "entry_bg": "#7E57C2",
        "entry_fg": "#FFFFFF",
        "entry_border": "#9575CD",
        "list_bg": "#7E57C2",
        "list_fg": "#FFFFFF",
        "list_selected_bg": "#FFD54F",
        "list_selected_fg": "#6A4FB6",
        "tooltip_bg": "#9575CD",
        "tooltip_fg": "#FFFFFF",
        "progressbar_bg": "#B39DDB",
        "progressbar_fg": "#FFD54F"
},
        catchphrases: {
        "app_title": "Flutter Earth - Twilight Sparkle",
        "view_HomeView": "Home",
        "view_MapView": "Map",
        "view_DownloadView": "Download",
        "view_SatelliteInfoView": "Satellite Info",
        "view_IndexAnalysisView": "Index Analysis",
        "view_VectorDownloadView": "Vector Download",
        "view_DataViewerView": "Data Viewer",
        "view_ProgressView": "Progress",
        "view_SettingsView": "Settings",
        "view_AboutView": "About",
        "view_HomeView_Welcome": "Welcome to the Magic of Friendship!",
        "view_HomeView_WelcomeUser": "Welcome, Princess %1!",
        "status_gee_ready": "Magic Engine: Ready",
        "status_gee_not_ready": "Magic Engine: Not Authenticated",
        "action_goto_map": "Go to Map",
        "action_goto_download": "Download Data",
        "action_goto_settings": "Settings",
        "dialog_title_info": "Information",
        "desc_SatelliteInfoView": "All the knowledge you need!",
        "header_satellite_category": "Satellite / Category",
        "header_type": "Type",
        "placeholder_select_satellite": "Select a satellite for details.",
        "about_hello_user": "Hello, Princess %1!",
        "about_hello_generic": "Hello, Friend!",
        "about_developed_by": "Developed by the Magic of Friendship.",
        "action_visit_website": "Visit the Library",
        "dialog_title_welcome": "Welcome, Princess!",
        "prompt_enter_name": "Please enter your name:",
        "placeholder_your_name": "Your name",
        "settings_group_theme": "Appearance",
        "settings_label_theme": "Theme:",
        "settings_label_theme_options": "Theme Options:",
        "settings_opt_catchphrases": "Use Friendship Catchphrases",
        "settings_opt_icons": "Show Magical Icons",
        "settings_opt_animations": "Enable Animated Magic",
        "settings_group_general": "General",
        "settings_label_output_dir": "Output Directory:",
        "settings_group_actions": "Actions",
        "action_reload_settings": "Reload Magic",
        "action_clear_cache": "Clear Spellbook & Logs",
        "dialog_msg_cleanup_complete": "Spellbook and logs cleared.",
        "dialog_title_cleanup_complete": "Cleanup Complete",
        "status_no_active_downloads": "No active downloads."
},
        options: {
        "use_character_catchphrases": true,
        "show_special_icons": true,
        "enable_animated_background": true
}
    },
    {
        name: 'rainbow_dash',
        display_name: 'Rainbow Dash',
        category: 'mlp',
        background: '#00BFFF',
        primary: '#FF0000',
        emoji: '🌈',
        icon: '🌈',
        splashEffect: 'rainbow',
        uiEffect: 'rainbowTrail',
        welcomeMessage: '20% Cooler!',
        splashText: 'Flutter Earth - Rainbow Dash',
        notificationMessage: 'Flutter Earth - Rainbow Dash',
        colors: {
        "background": "#00BFFF",
        "foreground": "#FFFFFF",
        "primary": "#FF0000",
        "secondary": "#FFFF00",
        "accent": "#00FF00",
        "error": "#FF1493",
        "success": "#00FF00",
        "text": "#FFFFFF",
        "text_subtle": "#B0E0E6",
        "disabled": "#BDBDBD",
        "widget_bg": "#1E90FF",
        "widget_border": "#FF0000",
        "text_on_primary": "#00BFFF",
        "button_bg": "#FF0000",
        "button_fg": "#FFFFFF",
        "button_hover_bg": "#FFFF00",
        "entry_bg": "#1E90FF",
        "entry_fg": "#FFFFFF",
        "entry_border": "#FF0000",
        "list_bg": "#1E90FF",
        "list_fg": "#FFFFFF",
        "list_selected_bg": "#FF0000",
        "list_selected_fg": "#FFFFFF",
        "tooltip_bg": "#FF0000",
        "tooltip_fg": "#FFFFFF",
        "progressbar_bg": "#B0E0E6",
        "progressbar_fg": "#FF0000"
},
        catchphrases: {
        "app_title": "Flutter Earth - Rainbow Dash",
        "view_HomeView": "Home",
        "view_MapView": "Map",
        "view_DownloadView": "Download",
        "view_SatelliteInfoView": "Satellite Info",
        "view_IndexAnalysisView": "Index Analysis",
        "view_VectorDownloadView": "Vector Download",
        "view_DataViewerView": "Data Viewer",
        "view_ProgressView": "Progress",
        "view_SettingsView": "Settings",
        "view_AboutView": "About",
        "view_HomeView_Welcome": "20% Cooler!",
        "view_HomeView_WelcomeUser": "Welcome, Speedster %1!",
        "status_gee_ready": "Weather Engine: Ready",
        "status_gee_not_ready": "Weather Engine: Not Authenticated",
        "action_goto_map": "Go to Map",
        "action_goto_download": "Download Data",
        "action_goto_settings": "Settings",
        "dialog_title_info": "Information",
        "desc_SatelliteInfoView": "Fast facts, fast downloads!",
        "header_satellite_category": "Satellite / Category",
        "header_type": "Type",
        "placeholder_select_satellite": "Select a satellite for details.",
        "about_hello_user": "Hey, %1!",
        "about_hello_generic": "Hey there!",
        "about_developed_by": "Developed at Sonic Rainboom speed!",
        "action_visit_website": "Visit the Cloudsdale",
        "dialog_title_welcome": "Welcome, Speedster!",
        "prompt_enter_name": "Please enter your name:",
        "placeholder_your_name": "Your name",
        "settings_group_theme": "Appearance",
        "settings_label_theme": "Theme:",
        "settings_label_theme_options": "Theme Options:",
        "settings_opt_catchphrases": "Use Dash Catchphrases",
        "settings_opt_icons": "Show Lightning Icons",
        "settings_opt_animations": "Enable Rainbow Animations",
        "settings_group_general": "General",
        "settings_label_output_dir": "Output Directory:",
        "settings_group_actions": "Actions",
        "action_reload_settings": "Reload Weather",
        "action_clear_cache": "Clear Skies & Logs",
        "dialog_msg_cleanup_complete": "Skies and logs cleared.",
        "dialog_title_cleanup_complete": "Cleanup Complete",
        "status_no_active_downloads": "No active downloads."
},
        options: {
        "use_character_catchphrases": true,
        "show_special_icons": true,
        "enable_animated_background": true
}
    },
    {
        name: 'pinkie_pie',
        display_name: 'Pinkie Pie',
        category: 'mlp',
        background: '#FF69B4',
        primary: '#FFD700',
        emoji: '🎉',
        icon: '🎉',
        splashEffect: 'confetti',
        uiEffect: 'partyConfetti',
        welcomeMessage: 'Let's get this party started!',
        splashText: 'Flutter Earth - Pinkie Pie',
        notificationMessage: 'Flutter Earth - Pinkie Pie',
        colors: {
        "background": "#FF69B4",
        "foreground": "#FFFFFF",
        "primary": "#FFD700",
        "secondary": "#00BFFF",
        "accent": "#FFB347",
        "error": "#FF1493",
        "success": "#FFD700",
        "text": "#FFFFFF",
        "text_subtle": "#FFB6C1",
        "disabled": "#BDBDBD",
        "widget_bg": "#FFB6C1",
        "widget_border": "#FFD700",
        "text_on_primary": "#FF69B4",
        "button_bg": "#FFD700",
        "button_fg": "#FF69B4",
        "button_hover_bg": "#FFB347",
        "entry_bg": "#FFB6C1",
        "entry_fg": "#FFFFFF",
        "entry_border": "#FFD700",
        "list_bg": "#FFB6C1",
        "list_fg": "#FFFFFF",
        "list_selected_bg": "#FFD700",
        "list_selected_fg": "#FF69B4",
        "tooltip_bg": "#FFD700",
        "tooltip_fg": "#FF69B4",
        "progressbar_bg": "#FFB6C1",
        "progressbar_fg": "#FFD700"
},
        catchphrases: {
        "app_title": "Flutter Earth - Pinkie Pie",
        "view_HomeView": "Home",
        "view_MapView": "Map",
        "view_DownloadView": "Download",
        "view_SatelliteInfoView": "Satellite Info",
        "view_IndexAnalysisView": "Index Analysis",
        "view_VectorDownloadView": "Vector Download",
        "view_DataViewerView": "Data Viewer",
        "view_ProgressView": "Progress",
        "view_SettingsView": "Settings",
        "view_AboutView": "About",
        "view_HomeView_Welcome": "Let's get this party started!",
        "view_HomeView_WelcomeUser": "Welcome, Party Pony %1!",
        "status_gee_ready": "Party Engine: Ready",
        "status_gee_not_ready": "Party Engine: Not Authenticated",
        "action_goto_map": "Go to Map",
        "action_goto_download": "Download Data",
        "action_goto_settings": "Settings",
        "dialog_title_info": "Information",
        "desc_SatelliteInfoView": "Fun facts and more!",
        "header_satellite_category": "Satellite / Category",
        "header_type": "Type",
        "placeholder_select_satellite": "Select a satellite for details.",
        "about_hello_user": "Hiya, %1!",
        "about_hello_generic": "Hiya, Friend!",
        "about_developed_by": "Developed with a party cannon!",
        "action_visit_website": "Visit Sugarcube Corner",
        "dialog_title_welcome": "Welcome, Party Pony!",
        "prompt_enter_name": "Please enter your name:",
        "placeholder_your_name": "Your name",
        "settings_group_theme": "Appearance",
        "settings_label_theme": "Theme:",
        "settings_label_theme_options": "Theme Options:",
        "settings_opt_catchphrases": "Use Party Catchphrases",
        "settings_opt_icons": "Show Party Icons",
        "settings_opt_animations": "Enable Party Animations",
        "settings_group_general": "General",
        "settings_label_output_dir": "Output Directory:",
        "settings_group_actions": "Actions",
        "action_reload_settings": "Reload Party",
        "action_clear_cache": "Clear Balloons & Logs",
        "dialog_msg_cleanup_complete": "Balloons and logs cleared.",
        "dialog_title_cleanup_complete": "Cleanup Complete",
        "status_no_active_downloads": "No active downloads."
},
        options: {
        "use_character_catchphrases": true,
        "show_special_icons": true,
        "enable_animated_background": true
}
    },
    {
        name: 'fluttershy',
        display_name: 'Fluttershy',
        category: 'mlp',
        background: '#FFFACD',
        primary: '#FFB6C1',
        emoji: '🦋',
        icon: '🦋',
        splashEffect: 'fade',
        uiEffect: 'none',
        welcomeMessage: 'Welcome, if that's okay...',
        splashText: 'Flutter Earth - Fluttershy',
        notificationMessage: 'Flutter Earth - Fluttershy',
        colors: {
        "background": "#FFFACD",
        "foreground": "#8B5E3C",
        "primary": "#FFB6C1",
        "secondary": "#B2DFDB",
        "accent": "#FFD700",
        "error": "#E57373",
        "success": "#AED581",
        "text": "#8B5E3C",
        "text_subtle": "#FFDAB9",
        "disabled": "#BDBDBD",
        "widget_bg": "#FFF8DC",
        "widget_border": "#FFB6C1",
        "text_on_primary": "#8B5E3C",
        "button_bg": "#FFB6C1",
        "button_fg": "#8B5E3C",
        "button_hover_bg": "#FFD700",
        "entry_bg": "#FFF8DC",
        "entry_fg": "#8B5E3C",
        "entry_border": "#FFB6C1",
        "list_bg": "#FFF8DC",
        "list_fg": "#8B5E3C",
        "list_selected_bg": "#FFB6C1",
        "list_selected_fg": "#8B5E3C",
        "tooltip_bg": "#FFB6C1",
        "tooltip_fg": "#8B5E3C",
        "progressbar_bg": "#FFDAB9",
        "progressbar_fg": "#FFB6C1"
},
        catchphrases: {
        "app_title": "Flutter Earth - Fluttershy",
        "view_HomeView": "Home",
        "view_MapView": "Map",
        "view_DownloadView": "Download",
        "view_SatelliteInfoView": "Satellite Info",
        "view_IndexAnalysisView": "Index Analysis",
        "view_VectorDownloadView": "Vector Download",
        "view_DataViewerView": "Data Viewer",
        "view_ProgressView": "Progress",
        "view_SettingsView": "Settings",
        "view_AboutView": "About",
        "view_HomeView_Welcome": "Welcome, if that's okay...",
        "view_HomeView_WelcomeUser": "Welcome, Kind Friend %1!",
        "status_gee_ready": "Kindness Engine: Ready",
        "status_gee_not_ready": "Kindness Engine: Not Authenticated",
        "action_goto_map": "Go to Map",
        "action_goto_download": "Download Data",
        "action_goto_settings": "Settings",
        "dialog_title_info": "Information",
        "desc_SatelliteInfoView": "Gentle facts and soft downloads.",
        "header_satellite_category": "Satellite / Category",
        "header_type": "Type",
        "placeholder_select_satellite": "Select a satellite for details.",
        "about_hello_user": "Oh, hello %1...",
        "about_hello_generic": "Oh, hello...",
        "about_developed_by": "Developed with kindness and care.",
        "action_visit_website": "Visit the Cottage",
        "dialog_title_welcome": "Welcome, Kind Friend!",
        "prompt_enter_name": "Please enter your name:",
        "placeholder_your_name": "Your name",
        "settings_group_theme": "Appearance",
        "settings_label_theme": "Theme:",
        "settings_label_theme_options": "Theme Options:",
        "settings_opt_catchphrases": "Use Gentle Catchphrases",
        "settings_opt_icons": "Show Butterfly Icons",
        "settings_opt_animations": "Enable Gentle Animations",
        "settings_group_general": "General",
        "settings_label_output_dir": "Output Directory:",
        "settings_group_actions": "Actions",
        "action_reload_settings": "Reload Kindness",
        "action_clear_cache": "Clear Meadows & Logs",
        "dialog_msg_cleanup_complete": "Meadows and logs cleared.",
        "dialog_title_cleanup_complete": "Cleanup Complete",
        "status_no_active_downloads": "No active downloads."
},
        options: {
        "use_character_catchphrases": true,
        "show_special_icons": true,
        "enable_animated_background": true
}
    },
    {
        name: 'rarity',
        display_name: 'Rarity',
        category: 'mlp',
        background: '#FFFFFF',
        primary: '#8E24AA',
        emoji: '💎',
        icon: '💎',
        splashEffect: 'fade',
        uiEffect: 'none',
        welcomeMessage: 'Welcome, darling!',
        splashText: 'Flutter Earth - Rarity',
        notificationMessage: 'Flutter Earth - Rarity',
        colors: {
        "background": "#FFFFFF",
        "foreground": "#8E24AA",
        "primary": "#8E24AA",
        "secondary": "#00BFFF",
        "accent": "#FFD700",
        "error": "#E57373",
        "success": "#AED581",
        "text": "#8E24AA",
        "text_subtle": "#B39DDB",
        "disabled": "#BDBDBD",
        "widget_bg": "#F3E5F5",
        "widget_border": "#8E24AA",
        "text_on_primary": "#FFFFFF",
        "button_bg": "#8E24AA",
        "button_fg": "#FFFFFF",
        "button_hover_bg": "#FFD700",
        "entry_bg": "#F3E5F5",
        "entry_fg": "#8E24AA",
        "entry_border": "#8E24AA",
        "list_bg": "#F3E5F5",
        "list_fg": "#8E24AA",
        "list_selected_bg": "#8E24AA",
        "list_selected_fg": "#FFFFFF",
        "tooltip_bg": "#8E24AA",
        "tooltip_fg": "#FFFFFF",
        "progressbar_bg": "#B39DDB",
        "progressbar_fg": "#8E24AA"
},
        catchphrases: {
        "app_title": "Flutter Earth - Rarity",
        "view_HomeView": "Home",
        "view_MapView": "Map",
        "view_DownloadView": "Download",
        "view_SatelliteInfoView": "Satellite Info",
        "view_IndexAnalysisView": "Index Analysis",
        "view_VectorDownloadView": "Vector Download",
        "view_DataViewerView": "Data Viewer",
        "view_ProgressView": "Progress",
        "view_SettingsView": "Settings",
        "view_AboutView": "About",
        "view_HomeView_Welcome": "Welcome, darling!",
        "view_HomeView_WelcomeUser": "Welcome, Fabulous %1!",
        "status_gee_ready": "Glamour Engine: Ready",
        "status_gee_not_ready": "Glamour Engine: Not Authenticated",
        "action_goto_map": "Go to Map",
        "action_goto_download": "Download Data",
        "action_goto_settings": "Settings",
        "dialog_title_info": "Information",
        "desc_SatelliteInfoView": "Fabulous facts and dazzling downloads.",
        "header_satellite_category": "Satellite / Category",
        "header_type": "Type",
        "placeholder_select_satellite": "Select a satellite for details.",
        "about_hello_user": "Hello, darling %1!",
        "about_hello_generic": "Hello, darling!",
        "about_developed_by": "Developed with style and grace.",
        "action_visit_website": "Visit the Boutique",
        "dialog_title_welcome": "Welcome, Fabulous Friend!",
        "prompt_enter_name": "Please enter your name:",
        "placeholder_your_name": "Your name",
        "settings_group_theme": "Appearance",
        "settings_label_theme": "Theme:",
        "settings_label_theme_options": "Theme Options:",
        "settings_opt_catchphrases": "Use Glamour Catchphrases",
        "settings_opt_icons": "Show Diamond Icons",
        "settings_opt_animations": "Enable Glamour Animations",
        "settings_group_general": "General",
        "settings_label_output_dir": "Output Directory:",
        "settings_group_actions": "Actions",
        "action_reload_settings": "Reload Glamour",
        "action_clear_cache": "Clear Gems & Logs",
        "dialog_msg_cleanup_complete": "Gems and logs cleared.",
        "dialog_title_cleanup_complete": "Cleanup Complete",
        "status_no_active_downloads": "No active downloads."
},
        options: {
        "use_character_catchphrases": true,
        "show_special_icons": true,
        "enable_animated_background": true
}
    },
    {
        name: 'applejack',
        display_name: 'Applejack',
        category: 'mlp',
        background: '#FFDE7D',
        primary: '#FF8C00',
        emoji: '🍎',
        icon: '🍎',
        splashEffect: 'fade',
        uiEffect: 'none',
        welcomeMessage: 'Howdy, partner!',
        splashText: 'Flutter Earth - Applejack',
        notificationMessage: 'Flutter Earth - Applejack',
        colors: {
        "background": "#FFDE7D",
        "foreground": "#8B5E3C",
        "primary": "#FF8C00",
        "secondary": "#228B22",
        "accent": "#FFD700",
        "error": "#E57373",
        "success": "#AED581",
        "text": "#8B5E3C",
        "text_subtle": "#FFDAB9",
        "disabled": "#BDBDBD",
        "widget_bg": "#FFE4B5",
        "widget_border": "#FF8C00",
        "text_on_primary": "#FFDE7D",
        "button_bg": "#FF8C00",
        "button_fg": "#FFDE7D",
        "button_hover_bg": "#FFD700",
        "entry_bg": "#FFE4B5",
        "entry_fg": "#8B5E3C",
        "entry_border": "#FF8C00",
        "list_bg": "#FFE4B5",
        "list_fg": "#8B5E3C",
        "list_selected_bg": "#FF8C00",
        "list_selected_fg": "#FFDE7D",
        "tooltip_bg": "#FF8C00",
        "tooltip_fg": "#FFDE7D",
        "progressbar_bg": "#FFDAB9",
        "progressbar_fg": "#FF8C00"
},
        catchphrases: {
        "app_title": "Flutter Earth - Applejack",
        "view_HomeView": "Home",
        "view_MapView": "Map",
        "view_DownloadView": "Download",
        "view_SatelliteInfoView": "Satellite Info",
        "view_IndexAnalysisView": "Index Analysis",
        "view_VectorDownloadView": "Vector Download",
        "view_DataViewerView": "Data Viewer",
        "view_ProgressView": "Progress",
        "view_SettingsView": "Settings",
        "view_AboutView": "About",
        "view_HomeView_Welcome": "Howdy, partner!",
        "view_HomeView_WelcomeUser": "Welcome, Honest %1!",
        "status_gee_ready": "Honesty Engine: Ready",
        "status_gee_not_ready": "Honesty Engine: Not Authenticated",
        "action_goto_map": "Go to Map",
        "action_goto_download": "Download Data",
        "action_goto_settings": "Settings",
        "dialog_title_info": "Information",
        "desc_SatelliteInfoView": "Down-to-earth facts and honest downloads.",
        "header_satellite_category": "Satellite / Category",
        "header_type": "Type",
        "placeholder_select_satellite": "Select a satellite for details.",
        "about_hello_user": "Howdy, %1!",
        "about_hello_generic": "Howdy!",
        "about_developed_by": "Developed with hard work and honesty.",
        "action_visit_website": "Visit Sweet Apple Acres",
        "dialog_title_welcome": "Welcome, Honest Friend!",
        "prompt_enter_name": "Please enter your name:",
        "placeholder_your_name": "Your name",
        "settings_group_theme": "Appearance",
        "settings_label_theme": "Theme:",
        "settings_label_theme_options": "Theme Options:",
        "settings_opt_catchphrases": "Use Honest Catchphrases",
        "settings_opt_icons": "Show Apple Icons",
        "settings_opt_animations": "Enable Farm Animations",
        "settings_group_general": "General",
        "settings_label_output_dir": "Output Directory:",
        "settings_group_actions": "Actions",
        "action_reload_settings": "Reload Honesty",
        "action_clear_cache": "Clear Barn & Logs",
        "dialog_msg_cleanup_complete": "Barn and logs cleared.",
        "dialog_title_cleanup_complete": "Cleanup Complete",
        "status_no_active_downloads": "No active downloads."
},
        options: {
        "use_character_catchphrases": true,
        "show_special_icons": true,
        "enable_animated_background": true
}
    },
    {
        name: 'derpy_hooves',
        display_name: 'Derpy Hooves',
        category: 'mlp',
        background: '#B0C4DE',
        primary: '#FFD700',
        emoji: '🧁',
        icon: '🧁',
        splashEffect: 'fade',
        uiEffect: 'none',
        welcomeMessage: 'Muffins for everypony!',
        splashText: 'Flutter Earth - Derpy Hooves',
        notificationMessage: 'Flutter Earth - Derpy Hooves',
        colors: {
        "background": "#B0C4DE",
        "foreground": "#6A5ACD",
        "primary": "#FFD700",
        "secondary": "#87CEEB",
        "accent": "#FFB347",
        "error": "#FF6347",
        "success": "#FFD700",
        "text": "#6A5ACD",
        "text_subtle": "#D3D3D3",
        "disabled": "#BDBDBD",
        "widget_bg": "#E6E6FA",
        "widget_border": "#FFD700",
        "text_on_primary": "#6A5ACD",
        "button_bg": "#FFD700",
        "button_fg": "#6A5ACD",
        "button_hover_bg": "#FFB347",
        "entry_bg": "#E6E6FA",
        "entry_fg": "#6A5ACD",
        "entry_border": "#FFD700",
        "list_bg": "#E6E6FA",
        "list_fg": "#6A5ACD",
        "list_selected_bg": "#FFD700",
        "list_selected_fg": "#6A5ACD",
        "tooltip_bg": "#FFD700",
        "tooltip_fg": "#6A5ACD",
        "progressbar_bg": "#D3D3D3",
        "progressbar_fg": "#FFD700"
},
        catchphrases: {
        "app_title": "Flutter Earth - Derpy Hooves",
        "view_HomeView": "Home",
        "view_MapView": "Map",
        "view_DownloadView": "Download",
        "view_SatelliteInfoView": "Satellite Info",
        "view_IndexAnalysisView": "Index Analysis",
        "view_VectorDownloadView": "Vector Download",
        "view_DataViewerView": "Data Viewer",
        "view_ProgressView": "Progress",
        "view_SettingsView": "Settings",
        "view_AboutView": "About",
        "view_HomeView_Welcome": "Muffins for everypony!",
        "view_HomeView_WelcomeUser": "Welcome, Muffin Lover %1!",
        "status_gee_ready": "Muffin Engine: Ready",
        "status_gee_not_ready": "Muffin Engine: Not Authenticated",
        "action_goto_map": "Go to Map",
        "action_goto_download": "Download Muffins",
        "action_goto_settings": "Settings",
        "dialog_title_info": "Information",
        "desc_SatelliteInfoView": "Muffin facts and more!",
        "header_satellite_category": "Satellite / Category",
        "header_type": "Type",
        "placeholder_select_satellite": "Select a satellite for details.",
        "about_hello_user": "Hiya, %1!",
        "about_hello_generic": "Hiya, Friend!",
        "about_developed_by": "Developed with muffins!",
        "action_visit_website": "Visit the Muffin Shop",
        "dialog_title_welcome": "Welcome, Muffin Lover!",
        "prompt_enter_name": "Please enter your name:",
        "placeholder_your_name": "Your name",
        "settings_group_theme": "Appearance",
        "settings_label_theme": "Theme:",
        "settings_label_theme_options": "Theme Options:",
        "settings_opt_catchphrases": "Use Muffin Catchphrases",
        "settings_opt_icons": "Show Muffin Icons",
        "settings_opt_animations": "Enable Muffin Animations",
        "settings_group_general": "General",
        "settings_label_output_dir": "Output Directory:",
        "settings_group_actions": "Actions",
        "action_reload_settings": "Reload Muffins",
        "action_clear_cache": "Clear Muffins & Logs",
        "dialog_msg_cleanup_complete": "Muffins and logs cleared.",
        "dialog_title_cleanup_complete": "Cleanup Complete",
        "status_no_active_downloads": "No active downloads."
},
        options: {
        "use_character_catchphrases": true,
        "show_special_icons": true,
        "enable_animated_background": true
}
    },
    {
        name: 'princess_luna',
        display_name: 'Princess Luna',
        category: 'mlp',
        background: '#191970',
        primary: '#8A2BE2',
        emoji: '🌙',
        icon: '🌙',
        splashEffect: 'stars',
        uiEffect: 'nightGlow',
        welcomeMessage: 'Welcome to the night!',
        splashText: 'Flutter Earth - Princess Luna',
        notificationMessage: 'Flutter Earth - Princess Luna',
        colors: {
        "background": "#191970",
        "foreground": "#E0E0FF",
        "primary": "#8A2BE2",
        "secondary": "#4169E1",
        "accent": "#00CED1",
        "error": "#B22222",
        "success": "#00FFCC",
        "text": "#E0E0FF",
        "text_subtle": "#B0C4DE",
        "disabled": "#4B4B6B",
        "widget_bg": "#23235B",
        "widget_border": "#8A2BE2",
        "text_on_primary": "#191970",
        "button_bg": "#8A2BE2",
        "button_fg": "#E0E0FF",
        "button_hover_bg": "#4169E1",
        "entry_bg": "#23235B",
        "entry_fg": "#E0E0FF",
        "entry_border": "#8A2BE2",
        "list_bg": "#23235B",
        "list_fg": "#E0E0FF",
        "list_selected_bg": "#8A2BE2",
        "list_selected_fg": "#E0E0FF",
        "tooltip_bg": "#8A2BE2",
        "tooltip_fg": "#E0E0FF",
        "progressbar_bg": "#23235B",
        "progressbar_fg": "#8A2BE2"
},
        catchphrases: {
        "app_title": "Flutter Earth - Princess Luna",
        "view_HomeView": "Home",
        "view_MapView": "Map",
        "view_DownloadView": "Download",
        "view_SatelliteInfoView": "Satellite Info",
        "view_IndexAnalysisView": "Index Analysis",
        "view_VectorDownloadView": "Vector Download",
        "view_DataViewerView": "Data Viewer",
        "view_ProgressView": "Progress",
        "view_SettingsView": "Settings",
        "view_AboutView": "About",
        "view_HomeView_Welcome": "Welcome to the night!",
        "view_HomeView_WelcomeUser": "Welcome, Dreamer %1!",
        "status_gee_ready": "Night Engine: Ready",
        "status_gee_not_ready": "Night Engine: Not Authenticated",
        "action_goto_map": "Go to Map",
        "action_goto_download": "Download Dreams",
        "action_goto_settings": "Settings",
        "dialog_title_info": "Information",
        "desc_SatelliteInfoView": "Dreamy facts and more!",
        "header_satellite_category": "Satellite / Category",
        "header_type": "Type",
        "placeholder_select_satellite": "Select a satellite for details.",
        "about_hello_user": "Good evening, %1!",
        "about_hello_generic": "Good evening!",
        "about_developed_by": "Developed under the moonlight!",
        "action_visit_website": "Visit the Dream Realm",
        "dialog_title_welcome": "Welcome, Dreamer!",
        "prompt_enter_name": "Please enter your name:",
        "placeholder_your_name": "Your name",
        "settings_group_theme": "Appearance",
        "settings_label_theme": "Theme:",
        "settings_label_theme_options": "Theme Options:",
        "settings_opt_catchphrases": "Use Dream Catchphrases",
        "settings_opt_icons": "Show Moon Icons",
        "settings_opt_animations": "Enable Night Animations",
        "settings_group_general": "General",
        "settings_label_output_dir": "Output Directory:",
        "settings_group_actions": "Actions",
        "action_reload_settings": "Reload Night",
        "action_clear_cache": "Clear Dreams & Logs",
        "dialog_msg_cleanup_complete": "Dreams and logs cleared.",
        "dialog_title_cleanup_complete": "Cleanup Complete",
        "status_no_active_downloads": "No active downloads."
},
        options: {
        "use_character_catchphrases": true,
        "show_special_icons": true,
        "enable_animated_background": true
}
    },
    {
        name: 'princess_celestia',
        display_name: 'Princess Celestia',
        category: 'mlp',
        background: '#FFF8E1',
        primary: '#FFD700',
        emoji: '☀️',
        icon: '☀️',
        splashEffect: 'sunbeams',
        uiEffect: 'sunshine',
        welcomeMessage: 'Let the sun shine bright!',
        splashText: 'Flutter Earth - Princess Celestia',
        notificationMessage: 'Flutter Earth - Princess Celestia',
        colors: {
        "background": "#FFF8E1",
        "foreground": "#FFB300",
        "primary": "#FFD700",
        "secondary": "#FFECB3",
        "accent": "#FF8A65",
        "error": "#E57373",
        "success": "#AED581",
        "text": "#FFB300",
        "text_subtle": "#FFE082",
        "disabled": "#BDBDBD",
        "widget_bg": "#FFFDE7",
        "widget_border": "#FFD700",
        "text_on_primary": "#FFF8E1",
        "button_bg": "#FFD700",
        "button_fg": "#FFB300",
        "button_hover_bg": "#FFECB3",
        "entry_bg": "#FFFDE7",
        "entry_fg": "#FFB300",
        "entry_border": "#FFD700",
        "list_bg": "#FFFDE7",
        "list_fg": "#FFB300",
        "list_selected_bg": "#FFD700",
        "list_selected_fg": "#FFF8E1",
        "tooltip_bg": "#FFD700",
        "tooltip_fg": "#FFB300",
        "progressbar_bg": "#FFE082",
        "progressbar_fg": "#FFD700"
},
        catchphrases: {
        "app_title": "Flutter Earth - Princess Celestia",
        "view_HomeView": "Home",
        "view_MapView": "Map",
        "view_DownloadView": "Download",
        "view_SatelliteInfoView": "Satellite Info",
        "view_IndexAnalysisView": "Index Analysis",
        "view_VectorDownloadView": "Vector Download",
        "view_DataViewerView": "Data Viewer",
        "view_ProgressView": "Progress",
        "view_SettingsView": "Settings",
        "view_AboutView": "About",
        "view_HomeView_Welcome": "Let the sun shine bright!",
        "view_HomeView_WelcomeUser": "Welcome, Radiant %1!",
        "status_gee_ready": "Sun Engine: Ready",
        "status_gee_not_ready": "Sun Engine: Not Authenticated",
        "action_goto_map": "Go to Map",
        "action_goto_download": "Download Sunlight",
        "action_goto_settings": "Settings",
        "dialog_title_info": "Information",
        "desc_SatelliteInfoView": "Radiant facts and more!",
        "header_satellite_category": "Satellite / Category",
        "header_type": "Type",
        "placeholder_select_satellite": "Select a satellite for details.",
        "about_hello_user": "Good day, %1!",
        "about_hello_generic": "Good day!",
        "about_developed_by": "Developed under the sun!",
        "action_visit_website": "Visit Canterlot",
        "dialog_title_welcome": "Welcome, Radiant Friend!",
        "prompt_enter_name": "Please enter your name:",
        "placeholder_your_name": "Your name",
        "settings_group_theme": "Appearance",
        "settings_label_theme": "Theme:",
        "settings_label_theme_options": "Theme Options:",
        "settings_opt_catchphrases": "Use Sun Catchphrases",
        "settings_opt_icons": "Show Sun Icons",
        "settings_opt_animations": "Enable Sun Animations",
        "settings_group_general": "General",
        "settings_label_output_dir": "Output Directory:",
        "settings_group_actions": "Actions",
        "action_reload_settings": "Reload Sun",
        "action_clear_cache": "Clear Sun & Logs",
        "dialog_msg_cleanup_complete": "Sun and logs cleared.",
        "dialog_title_cleanup_complete": "Cleanup Complete",
        "status_no_active_downloads": "No active downloads."
},
        options: {
        "use_character_catchphrases": true,
        "show_special_icons": true,
        "enable_animated_background": true
}
    },
    {
        name: 'starlight_glimmer',
        display_name: 'Starlight Glimmer',
        category: 'mlp',
        background: '#CE93D8',
        primary: '#00B8D4',
        emoji: '⭐',
        icon: '⭐',
        splashEffect: 'sunbeams',
        uiEffect: 'sunshine',
        welcomeMessage: 'Equality and friendship!',
        splashText: 'Flutter Earth - Starlight Glimmer',
        notificationMessage: 'Flutter Earth - Starlight Glimmer',
        colors: {
        "background": "#CE93D8",
        "foreground": "#00B8D4",
        "primary": "#00B8D4",
        "secondary": "#FFD54F",
        "accent": "#FFD700",
        "error": "#E57373",
        "success": "#AED581",
        "text": "#00B8D4",
        "text_subtle": "#B39DDB",
        "disabled": "#BDBDBD",
        "widget_bg": "#E1BEE7",
        "widget_border": "#00B8D4",
        "text_on_primary": "#CE93D8",
        "button_bg": "#00B8D4",
        "button_fg": "#CE93D8",
        "button_hover_bg": "#FFD54F",
        "entry_bg": "#E1BEE7",
        "entry_fg": "#00B8D4",
        "entry_border": "#00B8D4",
        "list_bg": "#E1BEE7",
        "list_fg": "#00B8D4",
        "list_selected_bg": "#FFD54F",
        "list_selected_fg": "#00B8D4",
        "tooltip_bg": "#00B8D4",
        "tooltip_fg": "#CE93D8",
        "progressbar_bg": "#B39DDB",
        "progressbar_fg": "#00B8D4"
},
        catchphrases: {
        "app_title": "Flutter Earth - Starlight Glimmer",
        "view_HomeView": "Home",
        "view_MapView": "Map",
        "view_DownloadView": "Download",
        "view_SatelliteInfoView": "Satellite Info",
        "view_IndexAnalysisView": "Index Analysis",
        "view_VectorDownloadView": "Vector Download",
        "view_DataViewerView": "Data Viewer",
        "view_ProgressView": "Progress",
        "view_SettingsView": "Settings",
        "view_AboutView": "About",
        "view_HomeView_Welcome": "Equality and friendship!",
        "view_HomeView_WelcomeUser": "Welcome, Equal %1!",
        "status_gee_ready": "Equality Engine: Ready",
        "status_gee_not_ready": "Equality Engine: Not Authenticated",
        "action_goto_map": "Go to Map",
        "action_goto_download": "Download Equality",
        "action_goto_settings": "Settings",
        "dialog_title_info": "Information",
        "desc_SatelliteInfoView": "Equal facts and more!",
        "header_satellite_category": "Satellite / Category",
        "header_type": "Type",
        "placeholder_select_satellite": "Select a satellite for details.",
        "about_hello_user": "Hello, %1!",
        "about_hello_generic": "Hello!",
        "about_developed_by": "Developed with equality!",
        "action_visit_website": "Visit Our Town",
        "dialog_title_welcome": "Welcome, Equal Friend!",
        "prompt_enter_name": "Please enter your name:",
        "placeholder_your_name": "Your name",
        "settings_group_theme": "Appearance",
        "settings_label_theme": "Theme:",
        "settings_label_theme_options": "Theme Options:",
        "settings_opt_catchphrases": "Use Equality Catchphrases",
        "settings_opt_icons": "Show Equality Icons",
        "settings_opt_animations": "Enable Equality Animations",
        "settings_group_general": "General",
        "settings_label_output_dir": "Output Directory:",
        "settings_group_actions": "Actions",
        "action_reload_settings": "Reload Equality",
        "action_clear_cache": "Clear Equality & Logs",
        "dialog_msg_cleanup_complete": "Equality and logs cleared.",
        "dialog_title_cleanup_complete": "Cleanup Complete",
        "status_no_active_downloads": "No active downloads."
},
        options: {
        "use_character_catchphrases": true,
        "show_special_icons": true,
        "enable_animated_background": true
}
    },
    {
        name: 'sunset_shimmer',
        display_name: 'Sunset Shimmer',
        category: 'mlp',
        background: '#FF7043',
        primary: '#FFD600',
        emoji: '🌅',
        icon: '🌅',
        splashEffect: 'fade',
        uiEffect: 'none',
        welcomeMessage: 'A new dawn, a new adventure!',
        splashText: 'Flutter Earth - Sunset Shimmer',
        notificationMessage: 'Flutter Earth - Sunset Shimmer',
        colors: {
        "background": "#FF7043",
        "foreground": "#FFD600",
        "primary": "#FFD600",
        "secondary": "#FFAB91",
        "accent": "#FF8A65",
        "error": "#E57373",
        "success": "#AED581",
        "text": "#FFD600",
        "text_subtle": "#FFAB91",
        "disabled": "#BDBDBD",
        "widget_bg": "#FFCCBC",
        "widget_border": "#FFD600",
        "text_on_primary": "#FF7043",
        "button_bg": "#FFD600",
        "button_fg": "#FF7043",
        "button_hover_bg": "#FFAB91",
        "entry_bg": "#FFCCBC",
        "entry_fg": "#FFD600",
        "entry_border": "#FFD600",
        "list_bg": "#FFCCBC",
        "list_fg": "#FFD600",
        "list_selected_bg": "#FFD600",
        "list_selected_fg": "#FF7043",
        "tooltip_bg": "#FFD600",
        "tooltip_fg": "#FF7043",
        "progressbar_bg": "#FFAB91",
        "progressbar_fg": "#FFD600"
},
        catchphrases: {
        "app_title": "Flutter Earth - Sunset Shimmer",
        "view_HomeView": "Home",
        "view_MapView": "Map",
        "view_DownloadView": "Download",
        "view_SatelliteInfoView": "Satellite Info",
        "view_IndexAnalysisView": "Index Analysis",
        "view_VectorDownloadView": "Vector Download",
        "view_DataViewerView": "Data Viewer",
        "view_ProgressView": "Progress",
        "view_SettingsView": "Settings",
        "view_AboutView": "About",
        "view_HomeView_Welcome": "A new dawn, a new adventure!",
        "view_HomeView_WelcomeUser": "Welcome, Shimmering %1!",
        "status_gee_ready": "Sunset Engine: Ready",
        "status_gee_not_ready": "Sunset Engine: Not Authenticated",
        "action_goto_map": "Go to Map",
        "action_goto_download": "Download Sunsets",
        "action_goto_settings": "Settings",
        "dialog_title_info": "Information",
        "desc_SatelliteInfoView": "Shimmering facts and more!",
        "header_satellite_category": "Satellite / Category",
        "header_type": "Type",
        "placeholder_select_satellite": "Select a satellite for details.",
        "about_hello_user": "Hello, %1!",
        "about_hello_generic": "Hello!",
        "about_developed_by": "Developed at sunset!",
        "action_visit_website": "Visit the Sunset",
        "dialog_title_welcome": "Welcome, Shimmering Friend!",
        "prompt_enter_name": "Please enter your name:",
        "placeholder_your_name": "Your name",
        "settings_group_theme": "Appearance",
        "settings_label_theme": "Theme:",
        "settings_label_theme_options": "Theme Options:",
        "settings_opt_catchphrases": "Use Sunset Catchphrases",
        "settings_opt_icons": "Show Sunset Icons",
        "settings_opt_animations": "Enable Sunset Animations",
        "settings_group_general": "General",
        "settings_label_output_dir": "Output Directory:",
        "settings_group_actions": "Actions",
        "action_reload_settings": "Reload Sunset",
        "action_clear_cache": "Clear Sunsets & Logs",
        "dialog_msg_cleanup_complete": "Sunsets and logs cleared.",
        "dialog_title_cleanup_complete": "Cleanup Complete",
        "status_no_active_downloads": "No active downloads."
},
        options: {
        "use_character_catchphrases": true,
        "show_special_icons": true,
        "enable_animated_background": true
}
    },
    {
        name: 'trixie',
        display_name: 'Trixie',
        category: 'mlp',
        background: '#7E57C2',
        primary: '#FFD700',
        emoji: '🎩',
        icon: '🎩',
        splashEffect: 'fade',
        uiEffect: 'none',
        welcomeMessage: 'The Great and Powerful Trixie!',
        splashText: 'Flutter Earth - Trixie',
        notificationMessage: 'Flutter Earth - Trixie',
        colors: {
        "background": "#7E57C2",
        "foreground": "#FFD700",
        "primary": "#FFD700",
        "secondary": "#9575CD",
        "accent": "#00B8D4",
        "error": "#E57373",
        "success": "#AED581",
        "text": "#FFD700",
        "text_subtle": "#B39DDB",
        "disabled": "#BDBDBD",
        "widget_bg": "#B39DDB",
        "widget_border": "#FFD700",
        "text_on_primary": "#7E57C2",
        "button_bg": "#FFD700",
        "button_fg": "#7E57C2",
        "button_hover_bg": "#9575CD",
        "entry_bg": "#B39DDB",
        "entry_fg": "#FFD700",
        "entry_border": "#FFD700",
        "list_bg": "#B39DDB",
        "list_fg": "#FFD700",
        "list_selected_bg": "#FFD700",
        "list_selected_fg": "#7E57C2",
        "tooltip_bg": "#FFD700",
        "tooltip_fg": "#7E57C2",
        "progressbar_bg": "#B39DDB",
        "progressbar_fg": "#FFD700"
},
        catchphrases: {
        "app_title": "Flutter Earth - Trixie",
        "view_HomeView": "Home",
        "view_MapView": "Map",
        "view_DownloadView": "Download",
        "view_SatelliteInfoView": "Satellite Info",
        "view_IndexAnalysisView": "Index Analysis",
        "view_VectorDownloadView": "Vector Download",
        "view_DataViewerView": "Data Viewer",
        "view_ProgressView": "Progress",
        "view_SettingsView": "Settings",
        "view_AboutView": "About",
        "view_HomeView_Welcome": "The Great and Powerful Trixie!",
        "view_HomeView_WelcomeUser": "Welcome, Spectacular %1!",
        "status_gee_ready": "Magic Engine: Ready",
        "status_gee_not_ready": "Magic Engine: Not Authenticated",
        "action_goto_map": "Go to Map",
        "action_goto_download": "Download Magic",
        "action_goto_settings": "Settings",
        "dialog_title_info": "Information",
        "desc_SatelliteInfoView": "Magical facts and more!",
        "header_satellite_category": "Satellite / Category",
        "header_type": "Type",
        "placeholder_select_satellite": "Select a satellite for details.",
        "about_hello_user": "Hello, %1!",
        "about_hello_generic": "Hello!",
        "about_developed_by": "Developed with magic!",
        "action_visit_website": "Visit the Stage",
        "dialog_title_welcome": "Welcome, Spectacular Friend!",
        "prompt_enter_name": "Please enter your name:",
        "placeholder_your_name": "Your name",
        "settings_group_theme": "Appearance",
        "settings_label_theme": "Theme:",
        "settings_label_theme_options": "Theme Options:",
        "settings_opt_catchphrases": "Use Magic Catchphrases",
        "settings_opt_icons": "Show Magic Icons",
        "settings_opt_animations": "Enable Magic Animations",
        "settings_group_general": "General",
        "settings_label_output_dir": "Output Directory:",
        "settings_group_actions": "Actions",
        "action_reload_settings": "Reload Magic",
        "action_clear_cache": "Clear Magic & Logs",
        "dialog_msg_cleanup_complete": "Magic and logs cleared.",
        "dialog_title_cleanup_complete": "Cleanup Complete",
        "status_no_active_downloads": "No active downloads."
},
        options: {
        "use_character_catchphrases": true,
        "show_special_icons": true,
        "enable_animated_background": true
}
    },
    {
        name: 'princess_cadence',
        display_name: 'Princess Cadence',
        category: 'mlp',
        background: '#F8BBD0',
        primary: '#BA68C8',
        emoji: '💖',
        icon: '💖',
        splashEffect: 'fade',
        uiEffect: 'none',
        welcomeMessage: 'Spread love everywhere you go!',
        splashText: 'Flutter Earth - Princess Cadence',
        notificationMessage: 'Flutter Earth - Princess Cadence',
        colors: {
        "background": "#F8BBD0",
        "foreground": "#BA68C8",
        "primary": "#BA68C8",
        "secondary": "#FFD54F",
        "accent": "#FFD700",
        "error": "#E57373",
        "success": "#AED581",
        "text": "#BA68C8",
        "text_subtle": "#F48FB1",
        "disabled": "#BDBDBD",
        "widget_bg": "#F3E5F5",
        "widget_border": "#BA68C8",
        "text_on_primary": "#F8BBD0",
        "button_bg": "#BA68C8",
        "button_fg": "#F8BBD0",
        "button_hover_bg": "#FFD54F",
        "entry_bg": "#F3E5F5",
        "entry_fg": "#BA68C8",
        "entry_border": "#BA68C8",
        "list_bg": "#F3E5F5",
        "list_fg": "#BA68C8",
        "list_selected_bg": "#BA68C8",
        "list_selected_fg": "#F8BBD0",
        "tooltip_bg": "#BA68C8",
        "tooltip_fg": "#F8BBD0",
        "progressbar_bg": "#F48FB1",
        "progressbar_fg": "#BA68C8"
},
        catchphrases: {
        "app_title": "Flutter Earth - Princess Cadence",
        "view_HomeView": "Home",
        "view_MapView": "Map",
        "view_DownloadView": "Download",
        "view_SatelliteInfoView": "Satellite Info",
        "view_IndexAnalysisView": "Index Analysis",
        "view_VectorDownloadView": "Vector Download",
        "view_DataViewerView": "Data Viewer",
        "view_ProgressView": "Progress",
        "view_SettingsView": "Settings",
        "view_AboutView": "About",
        "view_HomeView_Welcome": "Spread love everywhere you go!",
        "view_HomeView_WelcomeUser": "Welcome, Loving %1!",
        "status_gee_ready": "Love Engine: Ready",
        "status_gee_not_ready": "Love Engine: Not Authenticated",
        "action_goto_map": "Go to Map",
        "action_goto_download": "Download Love",
        "action_goto_settings": "Settings",
        "dialog_title_info": "Information",
        "desc_SatelliteInfoView": "Loving facts and more!",
        "header_satellite_category": "Satellite / Category",
        "header_type": "Type",
        "placeholder_select_satellite": "Select a satellite for details.",
        "about_hello_user": "Hello, %1!",
        "about_hello_generic": "Hello!",
        "about_developed_by": "Developed with love!",
        "action_visit_website": "Visit the Crystal Empire",
        "dialog_title_welcome": "Welcome, Loving Friend!",
        "prompt_enter_name": "Please enter your name:",
        "placeholder_your_name": "Your name",
        "settings_group_theme": "Appearance",
        "settings_label_theme": "Theme:",
        "settings_label_theme_options": "Theme Options:",
        "settings_opt_catchphrases": "Use Love Catchphrases",
        "settings_opt_icons": "Show Heart Icons",
        "settings_opt_animations": "Enable Love Animations",
        "settings_group_general": "General",
        "settings_label_output_dir": "Output Directory:",
        "settings_group_actions": "Actions",
        "action_reload_settings": "Reload Love",
        "action_clear_cache": "Clear Love & Logs",
        "dialog_msg_cleanup_complete": "Love and logs cleared.",
        "dialog_title_cleanup_complete": "Cleanup Complete",
        "status_no_active_downloads": "No active downloads."
},
        options: {
        "use_character_catchphrases": true,
        "show_special_icons": true,
        "enable_animated_background": true
}
    },
    {
        name: 'creeper',
        display_name: 'Creeper',
        category: 'minecraft',
        background: '#3A5F0B',
        primary: '#6FCF3D',
        emoji: '💣',
        icon: '💣',
        splashEffect: 'explode',
        uiEffect: 'creeperShake',
        welcomeMessage: 'Sss... Boom! Welcome!',
        splashText: 'Flutter Earth - Creeper',
        notificationMessage: 'Flutter Earth - Creeper',
        colors: {
        "background": "#3A5F0B",
        "foreground": "#FFFFFF",
        "primary": "#6FCF3D",
        "secondary": "#A9DFBF",
        "accent": "#1D8348",
        "error": "#E74C3C",
        "success": "#27AE60",
        "text": "#FFFFFF",
        "text_subtle": "#A9DFBF",
        "disabled": "#6C757D",
        "widget_bg": "#145A32",
        "widget_border": "#6FCF3D",
        "text_on_primary": "#3A5F0B",
        "button_bg": "#6FCF3D",
        "button_fg": "#3A5F0B",
        "button_hover_bg": "#A9DFBF",
        "entry_bg": "#145A32",
        "entry_fg": "#FFFFFF",
        "entry_border": "#6FCF3D",
        "list_bg": "#145A32",
        "list_fg": "#FFFFFF",
        "list_selected_bg": "#6FCF3D",
        "list_selected_fg": "#3A5F0B",
        "tooltip_bg": "#6FCF3D",
        "tooltip_fg": "#3A5F0B",
        "progressbar_bg": "#A9DFBF",
        "progressbar_fg": "#6FCF3D"
},
        catchphrases: {
        "app_title": "Flutter Earth - Creeper",
        "view_HomeView": "Home",
        "view_MapView": "Map",
        "view_DownloadView": "Download",
        "view_SatelliteInfoView": "Satellite Info",
        "view_IndexAnalysisView": "Index Analysis",
        "view_VectorDownloadView": "Vector Download",
        "view_DataViewerView": "Data Viewer",
        "view_ProgressView": "Progress",
        "view_SettingsView": "Settings",
        "view_AboutView": "About",
        "view_HomeView_Welcome": "Sss... Boom! Welcome!",
        "view_HomeView_WelcomeUser": "Welcome, Block Builder %1!",
        "status_gee_ready": "Creeper Engine: Ready",
        "status_gee_not_ready": "Creeper Engine: Not Authenticated",
        "action_goto_map": "Go to Map",
        "action_goto_download": "Download Blocks",
        "action_goto_settings": "Settings",
        "dialog_title_info": "Information",
        "desc_SatelliteInfoView": "Explosive facts and more!",
        "header_satellite_category": "Satellite / Category",
        "header_type": "Type",
        "placeholder_select_satellite": "Select a satellite for details.",
        "about_hello_user": "Sss... Hello, %1!",
        "about_hello_generic": "Sss... Hello!",
        "about_developed_by": "Developed with TNT!",
        "action_visit_website": "Visit the Cave",
        "dialog_title_welcome": "Welcome, Block Builder!",
        "prompt_enter_name": "Please enter your name:",
        "placeholder_your_name": "Your name",
        "settings_group_theme": "Appearance",
        "settings_label_theme": "Theme:",
        "settings_label_theme_options": "Theme Options:",
        "settings_opt_catchphrases": "Use Creeper Catchphrases",
        "settings_opt_icons": "Show TNT Icons",
        "settings_opt_animations": "Enable Explosive Animations",
        "settings_group_general": "General",
        "settings_label_output_dir": "Output Directory:",
        "settings_group_actions": "Actions",
        "action_reload_settings": "Reload TNT",
        "action_clear_cache": "Clear TNT & Logs",
        "dialog_msg_cleanup_complete": "TNT and logs cleared.",
        "dialog_title_cleanup_complete": "Cleanup Complete",
        "status_no_active_downloads": "No active downloads."
},
        options: {
        "use_character_catchphrases": true,
        "show_special_icons": true,
        "enable_animated_background": true
}
    }
];

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = availableThemes;
}
